// Bundles the site into one HTML file, dist/trackline.html, that opens
// straight from disk on macOS and Windows (double-click it). Run: npm run build
//
// The detailed gun models go next to it in dist/trackline-models.js (base64
// inside a plain script), because browsers refuse fetch() from file:// pages.
// Keep both files together; without the second one the simple guns are used.
import * as esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(root, 'dist');
fs.mkdirSync(out, { recursive: true });

const bundle = await esbuild.build({
  entryPoints: [path.join(root, 'js/main.js')],
  bundle: true,
  minify: true,
  format: 'iife',
  target: 'es2020',
  legalComments: 'none',
  write: false,
});
const js = bundle.outputFiles[0].text.replace(/<\/script/gi, '<\\/script').replace(/<!--/g, '<\\!--');
const css = fs.readFileSync(path.join(root, 'css/style.css'), 'utf8');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8')
  .replace(/<link rel="stylesheet" href="css\/style.css">/, () => `<style>\n${css}</style>`)
  .replace(/<script type="module" src="js\/main.js"><\/script>/, () => `<script src="trackline-models.js"></script>\n<script>\n/* three.js r186 (c) 2010-2026 Three.js Authors, MIT License */\n${js}</script>`);
const file = path.join(out, 'trackline.html');
fs.writeFileSync(file, html);
console.log(`wrote ${path.relative(root, file)} (${(html.length / 1024).toFixed(0)} KB)`);

const models = {};
for (const f of fs.readdirSync(path.join(root, 'models')).filter((n) => n.endsWith('.glb')).sort()) {
  models[f.replace(/\.glb$/, '')] = fs.readFileSync(path.join(root, 'models', f)).toString('base64');
}
const side = `// Detailed gun models for trackline.html (generated by build.mjs).\nwindow.TRACKLINE_MODELS = ${JSON.stringify(models, null, 0).replace(/","/g, '",\n"')};\n`;
const sideFile = path.join(out, 'trackline-models.js');
fs.writeFileSync(sideFile, side);
console.log(`wrote ${path.relative(root, sideFile)} (${(side.length / 1024 / 1024).toFixed(1)} MB, ${Object.keys(models).length} models)`);
